### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [dooshop/dooshop-gtm-tracking#2]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "data.shopId" and "time" when generating the url
let url = urlBase + data.shopId + '/tsa?typ=i&trc=default&ctg=sale&sid=checkout&tst=' + time;

**Comment by doo-kevin** [comment]
@praveena-pappu , issues are fixed and merged (thanks, @sahava!)
Shall we submit again or can you continue the review directly? Thanks in advance!

**Comment by praveena-pappu** [comment]
Hello, 

We see error with the encodeUriComponent for one of the fields "Error in encodeUriComponent. Argument uri has type number, which does not match required type string.". Please resolve the issue.
![dooshop_Error](https://user-images.githubusercontent.com/53495700/84807150-a8905d80-afbb-11ea-8c8b-9c44435c69c5.png)

**Comment by sahava** [comment]
Hi

I fixed this by removing the encoding for the `time` variable. As it's created with `getTimestamp()` (rounded with `Math.round()`), I don't see why it should be URI encoded, as the value is always predictably an integer number.
